apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "kongcloak.fullname" . }}-konga
  labels:
    app: {{ template "kongcloak.name" . }}-konga
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "kongcloak.name" . }}-konga
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "kongcloak.fullname" . }}-konga
          image: {{ .Values.images.keycloak.repository }}:{{ .Values.images.keycloak.tag }}
          imagePullPolicy: {{ .Values.images.keycloak.pullPolicy }}
          ports:
            - name: container
              containerPort: 1337
          env:
            - name: DB_ADAPTER
              value: postgres
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_database
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_username
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_password
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
