apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "kongcloak.fullname" . }}-kong
  labels:
    app: {{ template "kongcloak.name" . }}-kong
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "kongcloak.name" . }}-kong
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "kongcloak.fullname" . }}-kong
          image: {{ .Values.images.kong.repository }}:{{ .Values.images.kong.tag }}
          imagePullPolicy: {{ .Values.images.kong.pullPolicy }}
          ports:
            - name: container
              containerPort: 8000
            - name: admin
              containerPort: 8001
          env:
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_host
            - name: KONG_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_database
            - name: KONG_PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_port
            - name: KONG_PG_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_username
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kongcloak.fullname" . }}
                  key: postgres_password
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
